{% set name = "django-pipeline" %}
{% set version = "1.3.20" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "09e4711192a7b4a8bf18298f16b0688ed19a6a3019c2fa4afdaad9d3882661c7"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script_env:
    - VERSION_SUFFIX

requirements:
  host:
    - pip
    - python
  run:
    - futures >=2.1.3
    - python

test:
  # imports:
  #   - pipeline
  #   - pipeline.compilers
  #   - pipeline.compressors
  #   - pipeline.jinja2
  #   - pipeline.templatetags

about:
  home: "https://github.com/cyberdelia/django-pipeline"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Pipeline is an asset packaging library for Django."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - ome
