{% set name = "django-pipeline" %}
{% set version = "1.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "0ded22b974e3d627c27fc490ef5b23fcdcf0cdb00b704d628b5ca6d0b010d6fe"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script_env:
    - VERSION_SUFFIX

requirements:
  host:
    - pip
    - python =3
  run:
    - django
    - python =3

test:
  imports:
    - pipeline
    # - pipeline.compilers
    # - pipeline.compressors
    # - pipeline.jinja2
    # - pipeline.templatetags

about:
  home: "https://github.com/cyberdelia/django-pipeline"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Pipeline is an asset packaging library for Django."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - ome
